apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- namespace.yaml

images:
- name: coitlearning/coit-frontend
  newName: coitlearning/coit-frontend
  newTag: latest

commonLabels:
  environment: production
nameSuffix: -production
replicas:
  - name: coit-frontend
    count: 4

namespace: production-f