apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./coit-frontend-deployment.yaml
- ./coit-frontend-service.yaml
images:
- name: coitlearning/coit-frontend
  newTag: latest

configMapGenerator:
- name: coit-frontend-config
  envs:
  - application.properties

secretGenerator:
  - name: coit-frontend-secrets
    envs:
    - applicationsecrets.properties

commonLabels:
  app: coit-frontend
  managed-by: kustomize

labels:
  - pairs: 
      location: mumbai


