apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- namespace.yaml

images:
- name: coitlearning/coit-backend1
  newName: coitlearning/coit-backend1
  newTag: v11

commonLabels:
  environment: production
nameSuffix: -production
replicas:
  - name: coit-backend1
    count: 4

namespace: production-b